### ISSUE TITLE
Windows 10 version 32bit/64bit?

### ISSUE THREAD

**Issue by cavadias** [NinjaJc01/goRoku#1]
Hi! Thank you for your idea! Does this run on 32bit? I am on build Windows 10 home 1803.

Thank you!

**Comment by NinjaJc01** [comment]
Hi there!
This should run on 32bit Windows but you will need to compile it specifically for that - prefixing the go build command with GOARCH=386. The current builds are most likely both 64bit.

**Comment by cavadias** [comment]
Thx very much!!!
